### PR TITLE
Rails 5.2 support

### PR DESCRIPTION
**Pull request by aried3r**

### CODE REVIEW

**Comment by aried3r** [comment]
I am not entirely sure what causes the tests to fail with Rails 3.x. I know this is the easy way out, but would it be ok to drop old Rails versions for the next version of mail_form?

**Comment by tegon** [comment]
@aried3r Looks like it's failing because you've bumped the ruby versions in the Travis build.
I think you have to bump them into the `exclude` clauses too. For example, change `2.2.9` to `2.2.10` and `2.3.6` to `2.3.7` and so on. I've made a comment in one of them to help.

**Comment by aried3r** [comment]
🤦‍♂️  you're right, thanks! All the more reason to drop it so I can't make this mistake anymore ;)

**Comment by tegon** [comment]
@aried3r Yeah, I think it makes sense to drop it but that's a matter for other PR.
For now I think we're good to go, thank you!

**Pull request merged**
