### PR TITLE
Test with Ruby 2.6 on Travis CI

### PR DESCRIPTION
**Pull request by aried3r**

### CODE REVIEW

**Comment by aried3r** [comment]
Hey! As this PR shows the problems with older Ruby versions and newer Rubygems and bundler versions, may we take this as an opportunity to drop support for these Ruby versions and also older Rails versions?

mail_form is pretty mature and older versions of the gem will continue to work on older Ruby and Rails versions, but dropping these might make maintenance much easier in the future.

Might I also suggest turning on cron jobs on Travis CI so these kind of things would be noticed sooner?
screenshot 2019-02-18 at 11 49 20

Happy to discuss before I work on this PR more :)

**Comment by aried3r** [comment]
Friendly ping @tegon.

**Comment by mracos** [comment]
Thanks for the contribution 💙

I fixed travis' build with f57f86a39e73348c360916cc3651afe67014e960, so I think we are good to go with this PR as is and then later we can deprecate old ruby/rails versions when we do a major version bump, WDYT @aried3r?

**Comment by aried3r** [comment]
> later we can deprecate old ruby/rails versions when we do a major version bump

When would that time come? I don't have strong opinions on it, but if it makes maintaining this gem easier, I'm all for it. :)

**Comment by tegon** [comment]
> I don't have strong opinions on it, but if it makes maintaining this gem easier, I'm all for it. :)

Yeah, me neither. We have no plans for features to include in a new major version, so I guess when Rails 6 comes out we can cut a new one that supports the same versions as Rails 6.

**Pull request merged**
