### PR TITLE
Fixing the captcha issue

### LINKED ISSUE #50: Spam check not working in test/production?
As far as I can tell, at the moment the spam check works properly in development (raising an error), but forms will deliver as normal even if a captcha field is populated in other environments.

This wasn't the case in an older project running 1.5.1, but is the case in 1.6.0

### PR DESCRIPTION
**Pull request by kohrVid**
Added a `deliver` method that checks that messages sent aren't spam and
are valid so as to fix #50

### CODE REVIEW

**Comment by nashby** [comment]
The problem here is [`before_deliver`](https://github.com/plataformatec/mail_form/blob/master/lib/mail_form/delivery.rb#L19) call back I think since halting callback behaviour was changed in Rails 5. So I think the best solution here is to remove this callback just to avoid complexity of maintaining it both for Rails 4 and 5 and add `not_spam` check in the [delivery](https://github.com/plataformatec/mail_form/blob/master/lib/mail_form/shim.rb#L48) method.

@kohrVid I think there's no need in defining another `delivery` method. @lucasmazza what do you think?

**Comment by lucasmazza** [comment]
> I think the best solution here is to remove this callback just to avoid complexity of maintaining it both for Rails 4 and 5 and add not_spam check in the delivery method.

:+1: I guess wouldn't affect the public API, and we can cut the callbacks noise from the source code.

Also, we need a test case replicating the problem from #50 to make sure we are fixing this as expected (I don't recall if we have a production-like test for the spam checking).

**Comment by kohrVid** [comment]
Thank you both for your feedback! I've updated the PR with the callback removed which I agree is probably best as maintaining it seems to break compatibility with Ruby 1.9.

@lucasmazza, there do seem to be tests relating to the captcha in the `resource_test.rb` file. I think the changes to the callback behaviour in Rails 5 somehow stopped the tests from failing when they ought to have done. I noticed that when I added a terminator to the original callbacks that sort of fixed it (in that the tests started to fail when a spam checker wasn't added to the `deliver` method) but since I've removed the callback such a terminator is no longer necessary.

I've noticed that the Travis build now fails in some places due to a Nokogiri issue. Is that something that would need to be looked at as well?

**Comment by aried3r** [comment]
I actually had to adapt the `before_delivery` callback to make it work properly with Rails 5, see #54, especially https://github.com/plataformatec/mail_form/pull/54/commits/3ea84cfd7a9ad52b2a8b8e474f75ecc942b98a65.

**Pull request closed without merging**
